###

# curl --location 'http://localhost:8080/signin'
#--form 'username="maciekek@gmail.com"'
#--form 'password="qwe123qwe123"'
POST http://localhost:8080/signin
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="username"

maciekek@gmail.com
--WebAppBoundary
Content-Disposition: form-data; name="password"

qwe123qwe123
--WebAppBoundary--

###

